spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventorymgmtdb
    username: root
    password: welcome1
  jpa:
    show-sql: true
    generate-ddl: false
